### PR TITLE
Update bootstrap-sass url

### PR DESCRIPTION
**Pull request by jabranr**
Updated `bootstrap-sass` URL :+1:

### CODE REVIEW

**Comment by kevva** [comment]
Why?

**Comment by jabranr** [comment]
Basically, `bootstrap-sass` used to point to an unofficially maintained repo (at the time of #34, hence bootstrap-sass-official) but now both of these point to same official repo.

**Comment by kevva** [comment]
Yeah, and https://github.com/twbs/bootstrap-sass says you should install `bootstrap-sass` in their docs so I think we should keep it as is.

**Comment by jabranr** [comment]
FYI, therefore it is changed FROM `bootstrap-sass-official` TO `bootstrap-sass` in this PR!

**Pull request closed without merging**
